course:
  name: "Especialización Avanzada en JavaScript, TypeScript y Node.js"
  description: "Curso diseñado para ingenieros de sistemas con experiencia, enfocado en las mecánicas internas, optimización de rendimiento y arquitecturas avanzadas para lograr un dominio experto en JS, TS y Node.js."
  instruccionesIA: >
    Por cada iteración que tengas, vuelve a leer este yml en su totalidad.
    Para cada pregunta, proporciona una explicación detallada del concepto involucrado.
    Incluye ejemplos prácticos, analogías si es útil, advertencias comunes y mejores prácticas.
    Asegúrate de que la persona entienda el "por qué" y el "cómo" detrás de cada concepto.
    Siempre valida si desea una explicación más técnica o más sencilla, y adapta el lenguaje.
    Para cada tópico, genera 3 preguntas tipo examen que validen la comprensión profunda del concepto, no generes exámenes fáciles.
    Las preguntas deben ser desafiantes y requerir la aplicación o el análisis, no solo la memorización.
    Incluye una mezcla de:
      - Preguntas de opción múltiple con explicaciones detalladas para cada opción (correcta e incorrectas).
      - Preguntas de "verdadero o falso" que requieran justificación.
      - Preguntas abiertas que soliciten ejemplos de código, análisis de escenarios o explicación del "por qué".
    Asegúrate de que las preguntas abarquen diferentes aspectos del tema (funcionamiento interno, optimización, mejores prácticas, advertencias).
    Siempre proporciona la respuesta correcta y una explicación exhaustiva.
    Recuerda mencionar las prácticas sugeridas para cada subtema.
    Ignora los topics o subtopics marcados como completados.
    Tu tarea es seguir la hoja de ruta y no adelantar temas que aún no hemos cubierto
    Identifica si al tópico le hace falta contenido y sugiere que otro tema debería incluír el tópico
    Por cada término en español, incluye su traducción en inglés en paréntesis
    Incluye información adicional acerca de nuevas tecnologías o herramientas implementadas en ES6+
  target_audience:
    - "Ingeniero en Sistemas"
    - "9 años de experiencia en la industria del software"
    - "3 años de experiencia específica en JavaScript/TypeScript/Node.js"
  learning_goal: "Convertirse en un experto demostrable en estas tecnologías, capaz de diseñar, desarrollar y optimizar aplicaciones de alto rendimiento, entender el funcionamiento interno y demostrar este conocimiento en entornos profesionales exigentes y entrevistas."
  prerequisites_excluded:
    - "Variables"
    - "Ciclos"
    - "Condicionales"
    - "Conceptos básicos de programación"

  modules:
    - $include: ./module_1.yml
    - $include: ./module_2.yml
    - $include: ./module_3.yml
    - $include: ./module_4.yml
    - $include: ./module_5.yml
